version: '3.7'
services:
    db_laravel_api_tests:
        container_name: db_lara_api
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=laravel_api_tests"
            - "MYSQL_USER=laravel_tests"
            - "MYSQL_PASSWORD=laravel_tests"
            - "MYSQL_ROOT_PASSWORD=1234567"
            - "MYSQL_PORT=3306"
        ports:
            - 3306:3306
        networks:
            laravelAPITests:
                ipv4_address: 172.80.0.2

    app_laravel_api_tests:
        container_name: app_lara_api
        build:
            context: .
            dockerfile: app.Dockerfile
        working_dir: /var/www
        ports:
            - 8001:80
        volumes:
            - /var/www/storage
            - ./:/var/www
        env_file: '.env'
        environment:
            - "DB_HOST=db_laravel_api_tests"
            - "DB_PORT=3306"
        links:
            - db_laravel_api_tests
        depends_on:
            - db_laravel_api_tests
        networks:
            laravelAPITests:
                ipv4_address: 172.80.0.3

    nginx_laravel_api_tests:
        container_name: nginx_lara_api
        build:
            context: .
            dockerfile: web.Dockerfile
        ports:
            - 80:80
        links:
            - app_laravel_api_tests
        networks:
            - laravelAPITests
        volumes:
            - ./:/var/www
            - ./nginx/access.log:/var/log/nginx/access.log
            - ./nginx/error.log:/var/log/nginx/error.log
        networks:
            laravelAPITests:
                ipv4_address: 172.80.0.4

    redis:
        container_name: redis_lara_api
        image: redis:latest
        networks:
            laravelAPITests:
                ipv4_address: 172.80.0.5

networks:
    laravelAPITests:
        driver: bridge
        ipam:
            config:
                - subnet: 172.80.0.0/16
volumes:
    dbdata:
